/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-07-19 13:26:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcometobank_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <!-- CSS only -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("        integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://unpkg.com/@popperjs/core@2\"></script>\r\n");
      out.write("        <style>\r\n");
      out.write("            body{\r\n");
      out.write("                background-image: url(\"/Onlinebanking/myStyleFol/images/images/banking.jpg\");\r\n");
      out.write("                background-repeat: no-repeat;\r\n");
      out.write("                background-size: cover;\r\n");
      out.write("                background-attachment: fixed;\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("            strong{\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("                font-size: 25px;\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("           #well{\r\n");
      out.write("               margin-left: 7%;\r\n");
      out.write("           }\r\n");
      out.write("           .nav-item:hover{\r\n");
      out.write("               background-color: rgb(247, 34, 34);\r\n");
      out.write("               border-radius: 12px;\r\n");
      out.write("           }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body><br>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light container\">\r\n");
      out.write("            <a class=\"navbar-brand\" id=\"str\" href=\"login\"><strong>Virtusa Bank</strong></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\"\r\n");
      out.write("                aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                           Accounts\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Saving Account</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">bussines Accounnt</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">student Account</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li  class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            Loans\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Home Loan</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Bussiness Loan</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Study Loan</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Vehicle Loan</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Other Loan</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            Deposits\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Fixed Deposit</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Recuring Deposit</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">others</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\"\r\n");
      out.write("                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                           Card Service\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Credit Card Service</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Debit Card Service</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Create/register Card Service</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            Account Info\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"login\">Login Account</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"registerhere\">Signup/Create account</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"admlogin\">AdmLogin</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("<br><br>\r\n");
      out.write("<!----heading-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"card container bg-dark text-white\">\r\n");
      out.write("    <img src=\"/Onlinebanking/myStyleFol/images/images/index.gif\" width=\"cover\" height=\"600vh\" class=\"card-img\" alt=\"...\">\r\n");
      out.write("    <div class=\"card-img-overlay\">\r\n");
      out.write("        <h5 class=\"card-title\"> <strong>Virtusa bank</strong></h5>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"well\" class=\"row container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <img src=\"/Onlinebanking/myStyleFol/images/images/createaccount.jpg\" width=\"cover\" height=\"200px\" alt=\"...\">\r\n");
      out.write("                <h5 class=\"card-title\">Accounnts</h5>\r\n");
      out.write("                <p class=\"card-text\">With supporting text below as furter process</p>\r\n");
      out.write("                <a href=\"login\" class=\"btn btn-primary\">click here</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("            <img src=\"/Onlinebanking/myStyleFol/images/images/loan.jpg\" width=\"cover\" height=\"200px\" alt=\"...\">\r\n");
      out.write("                <h5 class=\"card-title\">All types of Loans</h5>\r\n");
      out.write("                <p class=\"card-text\"> home,bussines etc.. Loans</p>\r\n");
      out.write("                <a href=\"login\" class=\"btn btn-primary\">click here</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <img src=\"/Onlinebanking/myStyleFol/images/images/user.jpg\" width=\"cover\" height=\"200px\" alt=\"...\">\r\n");
      out.write("                <h5 class=\"card-title\"> Card Services</h5>\r\n");
      out.write("                <p class=\"card-text\">  card all types of services </p>\r\n");
      out.write("                <a href=\"login\" class=\"btn btn-primary\">click here</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><br>\r\n");
      out.write("<div id=\"well\" class=\"row container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("            <img src=\"/Onlinebanking/myStyleFol/images/images/cashwithdrew.jpg\" width=\"cover\" height=\"200px\" alt=\"...\">\r\n");
      out.write("                <h5 class=\"card-title\">Banking Service</h5>\r\n");
      out.write("                <p class=\"card-text\"> by using this u can transfer and deposit money </p>\r\n");
      out.write("                <a href=\"login\" class=\"btn btn-primary\">click here</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<!-------main32-->\r\n");
      out.write("<div class=\"card container mb-3\">\r\n");
      out.write("    <img src=\"/Onlinebanking/myStyleFol/images/images/footer2.jpg\" width=\"cover\" height=\"150vh\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">one of the top 5 list our bank also</h5>\r\n");
      out.write("        <p class=\"card-text\">we hope You trust us.</p>\r\n");
      out.write("        <a href=\"devlopers\">App Developed by</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
